### ISSUE TITLE
High Systemload by Papercut

### ISSUE THREAD

**Issue by Hackwar** [ChangemakerStudios/Papercut-SMTP#255] opened 2023-09-08 08:07 UTC
**Describe the bug**
I had Papercut running in the background continously and while I had hardly any mails in the inbox, it regularly created spikes in the CPU usage, but more importantly it continously read ~20MB/s of data from my SSD. That resulted in my SSD getting very hot and after a few hours of running the notebook without Papercut in the background, the temperature is indeed a lot lower. (Yes, the thermal construction of my notebook is bad.) In any way, I would expect there to be next to no activity from Papercut when idling. Side note: I'm rarely restarting my computer, but put it in hibernation each time. Maybe that has something to do with that?

**To Reproduce**
I have no idea.

**Expected behavior**
Next to no CPU and especially SSD load when idling.

**Screenshots**
Didn't create them at the time.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 11

**Additional context**

**Comment by jzabroski** [comment] 2023-09-26 13:18
> **To Reproduce**
> I have no idea.

If you spend enough time to care about this, could you spend the time to also compile it and run it locally with a profiling tool like Redgate ANTS Profiler?  Note, I am not a contributor on this project, I am always just stunned when professional software developers complain about performance but offer absolutely nothing substantive in their performance complaints, but want other software developers to investigate heresy performance issues. The thermal construction of your notebook is irrelevant here. Bring data.

> it regularly created spikes in the CPU usage

What did you do to measure this? What was the duration of the spike?  

> it continously read ~20MB/s of data from my SSD

How did you determine the reads came from Papercut and not from, say, your antivirus/antimalware service?

You may want to pick up a copy of The Every Computer Performance Book to get started learning about computer performance so that you can contribute more useful information. Windows Task Manager is not a great source of information to report performance problems unless it's a very stark problem like "CPU stays pegged at 100% for 2 minutes".

**Comment by jzabroski** [comment] 2023-09-27 00:26
Initial thought was, looking at your screenshot, to search Google for "webview2 memory leak". Found this: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1633#issuecomment-1285697164

It's very possible that webview2 isn't the culprit, BTW. But that would be where to look first. 

See, even your sharing that screenshot was way more helpful than "I have no idea". By the way, I did explain a helpful resource to learning about performance troubleshooting - and it definitely isn't second nature to me. But this is a free project. It seems obvious to me users should have etiquette to be helpful as possible in reporting bugs and steer clear of anecdotes. I'm sorry you disagree. 🤷

**Comment by Hackwar** [comment] 2023-09-27 08:53
> > **To Reproduce**
> > I have no idea.
> 
> If you spend enough time to care about this, could you spend the time to also compile it and run it locally with a profiling tool like Redgate ANTS Profiler?

I don't have the toolchain to do that and no, I don't care enough to invest days into learning all the ins and outs of this project. Similarly how you don't give a f--k about my FOSS project.

> > it regularly created spikes in the CPU usage
> 
> What did you do to measure this? What was the duration of the spike?
> 
> > it continously read ~20MB/s of data from my SSD
> 
> How did you determine the reads came from Papercut and not from, say, your antivirus/antimalware service?

So, I've been having issues with my notebook for the last 2 years. The fan is constantly spinning on high rpm, the whole system gets very hot. I replaced the fan 2 times and got the whole mainboard, heatpipes and fan replaced under warranty recently. I keep my notebook in a very well ventilated position and regularly clean the cooler. I checked my whole software stack, from UEFI BIOS over Windows, drivers and all my other tools, like IDE and Windows Defender. None of this made a real difference. Then I killed the Papercut process and all of a sudden my problems were solved. I invested way to much time into this already. I had the courtesy of reporting this issue and that's it. I learned from this, that I'm not going to leave Papercut running in the background and I couldn't care less how qualified you think my report is.

**Comment by jzabroski** [comment] 2023-09-27 19:17
> So, I've been having issues with my notebook for the last 2 years.

...you did not even mention what version of Papercut you have installed. What good does it do if you are on a version of Papercut that is 2 or more years old and are reporting a bug with it without upgrading? This is etiquette for an open source project.  Connect the dots and read the link I posted - there was a bug in WebView2 that is likely causing your problem, not papercut.

**Comment by Payn** [comment] 2024-03-22 13:31
> Initial thought was, looking at your screenshot, to search Google for "webview2 memory leak". Found this: [MicrosoftEdge/WebView2Feedback#1633 (comment)](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1633#issuecomment-1285697164)
> 
> It's very possible that webview2 isn't the culprit, BTW. But that would be where to look first. https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1462.37 is ten months old.
> 
> See, even your sharing that screenshot was way more helpful than "I have no idea". By the way, I did explain a helpful resource to learning about performance troubleshooting - and it definitely isn't second nature to me. But this is a free project. It seems obvious to me users should have etiquette to be helpful as possible in reporting bugs and steer clear of anecdotes. I'm sorry you disagree. 🤷

Seems like a memory leak indeed. Related: https://github.com/ChangemakerStudios/Papercut-SMTP/issues/241

**Comment by victorromeo** [comment] 2024-04-11 04:05
Papercut.smtp version 6.2.0.0 on Windows Server 2019
![image](https://github.com/ChangemakerStudios/Papercut-SMTP/assets/3838993/e756642d-96a5-4368-811b-7d75db2f2f0e)

I just don't understand how these WebView2 processes consume so much CPU.  I agree with the assumption of a memory leak, but the cause eludes me.  The smtp service can hang occassionally, and I have to kill the process, to get it going again.  Typically the locking issue happens after several days of use however, so diagnostic debugging isn't great at this point.

**Comment by Jaben** [comment] 2024-05-14 00:29
I think this may have been fixed by PR #266

**Comment by Payn** [comment] 2024-08-10 15:50
Memory consumption seems to be fixed now. Can't comment on CPU usage as i never had that issue.

**Comment by Jaben** [comment] 2024-10-20 02:03
Released v7.0 which I believe fixes this issue. Closing for now. Please re-open if you're still having problems.

**Closed by Jaben** 2024-10-20 02:03 UTC
