### ISSUE TITLE
Clicking on a link creates 2 requests

### ISSUE THREAD

**Issue by orjandh** [ChangemakerStudios/Papercut-SMTP#234] opened 2022-11-24 15:09 UTC
**Describe the bug**
Clicking on a html anchor link in the "Message" view of a message sends 2 requests to the server.

**To Reproduce**
1. Set up a HTTP server or use https://webhook.site/ to inspect incoming requests.
2. Receive a message with the following text:
`<a href="{{link}}">{{link}}</a>`
1. Open the message in the "Message" viewer.
3. Click the anchor to open link.
4. Verify on server that 2 requests was sent.

**Expected behavior**
I expect there to only be 1 request when clicking a link.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 6.2.0

**Additional context**
Maybe the issue is that the request is already sent when the NavigationStarting event is fired, so cancelling this event only has effects on the UI. https://github.com/ChangemakerStudios/Papercut-SMTP/blob/a1727a60f9b6fe274bc2178b1dc5f2a76aa35276/src/Papercut.UI/ViewModels/MessageDetailHtmlViewModel.cs#L193

As a side note, this does not happen if opening the link by pressing ctrl and clicking the link on the "Raw" or "Body" views in PaperCut.

**Comment by Jaben** [comment] 2022-12-14 03:10
I can't reproduce... Can you provide a screen shot of where you're seeing the multiple requests "on the server"?

Thanks.

**Comment by RickKukiela** [comment] 2023-05-16 18:56
So this "bug" just cost me like 3 hours of dev time on a project because it was messing with my requests. The phantom first link was executing the action and then the 2nd real request would fail (rightfully) because the first "phantom" request already did the action the link that was "emailed" to me was supposed to do.

The trick to the bug and why some may not be able to reproduce it, it seems is a default browser configuration issue. If you use EDGE as your default browser, then it's likely that you cannot reproduce this bug.

My default browser is Chrome. When I click a link that was "emailed" to my papercut receptacle, I see two requests almost simulaniously on my server with two different user agents:

The first (phantom) request I get:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42`

The 2nd request which I see open in my chrome:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

It seems like somehow papercut is trying to open the request in Edge, but my system knows chrome is my default browser so then it passes the "Job" to open the link to chrome, but never stops the Edge api from making the web request. It never actually creates an Edge window though, so you would never know this request was happening unless its messing with the secondary request being fulfilled by chrome by performing the action first breaking the action attempt for the chrome request.

I was only able to finally figure this out by putting a request logger directly in my app entry point...

At least I'm aware of this so I wont waste more time on this but this is a real gnarly bug.

**Comment by RickKukiela** [comment] 2024-08-16 20:18
Welp... Here I am over a year later and just lost another hour of my life because of this bug... Because I completely forgot it was a thing.

Can someone please look into this?

**Comment by Jaben** [comment] 2024-09-25 04:53
I still can't reproduce this problem. Has anyone else had this issue?

**Comment by RickKukiela** [comment] 2024-09-25 17:15
@Jaben I recorded a video that demonstrates the issue and how to replicate / prove the issue is happening. Please give this a watch and let me know if it helps...

https://vimeo.com/1012853915/5da80dc25b?ts=0&share=copy

**Comment by Jaben** [comment] 2024-09-29 17:56
@RickKukiela thanks for the video -- that helped. Yeah, I see the problem as WebView2 appears to start the request to the same URL before I tell it to Cancel, not very useful.

Anyway, I think have a fix for it -- please give it a shot.

**Comment by RickKukiela** [comment] 2024-10-01 20:05
@Jaben I'm so glad you were able to make progress on this! I would love to try it, but I do not see a new release with the change available for download. Could you provide a link?

Thanks!

**Comment by RickKukiela** [comment] 2024-10-08 18:49
@Jaben Just pinging you on this in case you didn't see my last comment - no big deal if you're busy - I understand completely. I won't ping again on this and just wait patiently for a response :)

**Comment by orjandh** [comment] 2024-10-09 08:10
I have now tested the fix and it fixes the issue of my end. At the previous commit, the issue still happens, but when checking out in the fix commit, it no longer happens.

**Comment by RickKukiela** [comment] 2024-10-09 17:06
@orjandh are you compiling this yourself? How do I get a fixed exe?

**Comment by orjandh** [comment] 2024-10-10 07:28
I just open the solution in Visual Studio and run the project. You should probably need .Net framework installed.

**Comment by Jaben** [comment] 2024-10-19 03:15
> @orjandh are you compiling this yourself? How do I get a fixed exe?

I just Released v7.0.0. The fix is in this version.

**Comment by Jaben** [comment] 2024-10-20 02:04
Closing this issue as it's fixed in v7.0 release. Re-open if you continue to have problems.

**Closed by Jaben** 2024-10-20 02:04 UTC
