### ISSUE TITLE
arm64 Docker image

### ISSUE THREAD

**Issue by jkevingutierrez** [ChangemakerStudios/Papercut-SMTP#275] opened 2024-08-28 17:10 UTC
**Describe the bug**
The docker image doesn't have an arm64 version.

**To Reproduce**
1. Run `docker run -p 8080:80 -p 25:25 changemakerstudiosus/papercut-smtp:latest` on a mac with an M1, M2 or M3 chip without rosetta installed.
2. See error: `WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
3. Docker container won't initiate.

**Expected behavior**
Running changemakerstudiosus/papercut-smtp:latest docker image in an arm64 chip should work well.

**Desktop (please complete the following information):**
 - OS:  macOS
 - Version 14.6.1 (23G93)

**Comment by Jaben** [comment] 2024-09-13 04:14
I'm very new to this -- but I built a multi-platform image. Please give it a try:

``` changemakerstudiosus/papercut-smtp:7.0.0-rc1-multi```

**Comment by Jaben** [comment] 2024-09-20 01:33
Closing as others have said the issue is fixed.

**Closed by Jaben** 2024-09-20 01:33 UTC
